### ISSUE TITLE
Changing TLD path in setup results in error

### ISSUE THREAD

**Issue by xadox-1st** [danmons/retronas#11]
I have installed RetroNAS on a privileged Proxmox lxc with Ubuntu 20.04 LTS.
After that I was trying to setup the top level directory. But that results in an error:

_Can't make new window at (-1,21), size (24,80)._

So I setup the path manually in the 

_/opt/retronas/ansible/retronas_vars.yml_

Installing Mister_FPGA worked but trying to change the path again with the gui still did not work.

**Comment by birdybro** [comment]
Might be something kernel access related as Proxmox has limitations due to security.

https://pve.proxmox.com/wiki/Linux_Container

`For security reasons, access to host resources needs to be restricted. Therefore, containers run in their own separate namespaces. Additionally some syscalls (user space requests to the Linux kernel) are not allowed within containers. `

**Comment by xadox-1st** [comment]
Thx for the feedback.
Switching to Debian 11 solved the problem.
