### ISSUE TITLE
New S32X core not working with share

### ISSUE THREAD

**Issue by keltoigael** [danmons/retronas#172]
The recently released s32x core is not seeing the 32x folder in retronas. Tried updating, unmounting and mounting. 

Thanks!

**Comment by citizen-why** [comment]
As a note - I'm seeing the S32X roms folder - but its showing up as a directory in /mister/ as opposed to a symlink to /roms/sega/32x/.

The links in /mister/saves/, /mister/savestates/, /mister/BIOS/ are missing altogether

**Comment by sairuk** [comment]
I just run the MiSTer install clean this morning and its created the correct link, can you rename the folder and rerun the MiSTer installer then report back? 

```
19 Apr 22 22:37  /data/retronas/mister/games/S32X -> ../../roms/sega/32x
```

BIOS/saves links wont be created by default (we haven't added it) it requires an edited playbook to enable as [we discussed](https://github.com/danmons/retronas/discussions/60#discussioncomment-2444763)

I have not added it as the default yet because I think we need to do some comms for folks who have been running RetroNAS for a while before enabling, This is because as far as a I am aware, doing so will override the BIOS/saves availability on MiSTer perhaps @birdybro could confirm for me. If not i can push the change as the default

**Comment by keltoigael** [comment]
Can confirm after running the install things mister samba installer again fixed the mapping issue. s32x core now see's roms properly. Side note, if both of my misters could cross save via retronas that would be amazing, as mentioned above.

**Comment by citizen-why** [comment]
Worked for me as well!

**Comment by sairuk** [comment]
thanks all, closing
