### ISSUE TITLE
Failure to remove directory when using retronas and MiSTer

### ISSUE THREAD

**Issue by jonasrosland** [danmons/retronas#199]
Hi!

Just getting started with retronas, and connected my MiSTer setup to it over CIFS.
When I run `downloader.sh`, it tries to remove the empty folder for ATARI2600, but ends up failing:
```
Deleting empty folder /media/fat/games/ATARI2600
Traceback (most recent call last):
  File "/tmp/dont_download.zip/downloader/main.py", line 37, in main
    exit_code = execute_full_run(
  File "/tmp/dont_download.zip/downloader/main.py", line 57, in execute_full_run
    exit_code = runner.full_run()
  File "/tmp/dont_download.zip/downloader/full_run_service.py", line 59, in full_run
    result = self._full_run_impl()
  File "/tmp/dont_download.zip/downloader/full_run_service.py", line 121, in _full_run_impl
    self._online_importer.download_dbs_contents(importer_command, full_resync)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 108, in download_dbs_contents
    self._remove_folders(importer_command)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 210, in _remove_folders
    system_file_system.remove_folder(full_folder_path)
  File "/tmp/dont_download.zip/downloader/file_system.py", line 239, in remove_folder
    os.rmdir(self._path(path))
NotADirectoryError: [Errno 20] Not a directory: '/media/fat/games/ATARI2600'
```
This makes the rest of the update/download fail as well.
Creating an empty file in the ATARI2600 folder removes this failure point.

**Comment by danmons** [comment]
I'm an `update_all.sh` user, not really familiar with `downloader.sh`.  It's here if you want to try it:
* https://github.com/theypsilon/Update_All_MiSTer

Deleting empty directories seems a bit odd.  I suspect the reason it fails on RetroNAS specifically is because directories aren't directories, but rather symlinks.  It seems like that script can't detect the difference.

I'd potentially look at this option, copy/pasted from the readme.md, edit the following in `/media/fat/downloader.ini`:

```
; allow_reboot options:
;   0 -> Don't allow this tool to ever reboot automatically.
;   1 -> Allow this tool to reboot the system after any system file has been updated.
;   2 -> Allow this tool to reboot the system only after Linux has been updated.
allow_reboot = 1
```

That's the default.  Try setting it to `2` so that it only deletes old/stale cores, and not other content.  See how you go.

**Comment by sairuk** [comment]
See Dan's advice that should work around the issue but ultimately the downloader.sh should catch and handle this situation (directory vs link) so it would be worthwhile raising these troubles with the main project.

**Comment by jonasrosland** [comment]
Great suggestions, I'll open an issue in the repo for the downloader, as that's now replaced the update.sh script and is in Mr. Fusion by [default since 2.5](https://github.com/MiSTer-devel/mr-fusion/releases/tag/v2.5).

**Comment by sairuk** [comment]
main project is now tracking this so i'm closing it here
