### ISSUE TITLE
Unable to install retronas services. Error: A TLS fatal alert has been received.

### ISSUE THREAD

**Issue by fredkht** [danmons/retronas#233]
Hi, nowadays there's no way for me to install services and update my retronas core as there will be an error code prompt, which is "Failed, please check log screen."
I went to check services to check the cockpit web services, and the service log indicated as, 
"cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received."

May I know is there any solution that I can fix this issue?
Thanks

![Retronas 1](https://user-images.githubusercontent.com/111871240/186145181-74334523-613a-493a-81ad-ccdadd62917d.png)
![Retronas 2](https://user-images.githubusercontent.com/111871240/186145212-20736197-732a-499d-96a1-02c46e1014b3.png)
![Retronas 3](https://user-images.githubusercontent.com/111871240/186145234-76c1430b-01dc-4d47-9416-fef64edbaf1c.png)
![Retronas 4](https://user-images.githubusercontent.com/111871240/186145247-2215f90d-5f70-467f-a85b-b66f2f41c31f.png)
.

**Comment by sairuk** [comment]
The experimental webui isn't supported through this core retronas repository, please check if you can install services through the official text ui menu by running `retronas` in the terminal screen.

I did test the experimental ui locally and it works without issue here in firefox and chrome, what browser are you using?

**Comment by fredkht** [comment]
Last time it did work for me by installing services through the experimental ui.
Its just recently that it doesn't work anymore.
I have tried both chrome and Edge but both give me the same error.

**Comment by fredkht** [comment]
Is there any method that I can follow to uninstall the experimental ui if this is the culprit?

**Comment by sairuk** [comment]
The experimental ui is not the culprit here, it doesn't do anything with TLS, this is a cockpit/browser level issue. I just mentioned that it is not supported here for clarification

I just installed and tried chrome as well which is fine here. What OS are you trying to use Cockpit from?

As per the error prompt please also try again with the javascript console open (ctrl+shift+j) and capture any errors to see if it gives any clues

**Comment by fredkht** [comment]
> The experimental ui is not the culprit here, i don't think. It doesn't do anything with TLS, this seems like a cockpit/browser/os level issue. I just mentioned that it is not supported here for clarification
> 
> I just installed and tried chrome as well which is fine here. What OS are you trying to use Cockpit from?
> 
> As per the error prompt please also try again with the javascript console open (ctrl+shift+j) and capture any errors to see if it gives any clues

Sure, I'm using Chrome on Windows 10 OS.
Please see the captures on the errors
![Retronas 5](https://user-images.githubusercontent.com/111871240/186367569-506924ed-e8b5-45d9-a5bd-22dc9f3239bb.png)
.

**Comment by sairuk** [comment]
hrrm not much there, I'm stumped. I don't have Win10 available to check so I'll need to find a way of confirming the behaviour

Chrome 104 on Debian Linux works OK on a fresh install

Please go to terminal and run `retronas` and try and install something from the TUI to confirm retronas generally functions OK for you in the meantime

**Comment by fredkht** [comment]
> hrrm not much there, I'm stumped. I don't have Win10 available to check so I'll need to find a way of confirming the behaviour
> 
> Chrome 104 on Debian Linux works OK on a fresh install
> 
> Please go to terminal and run `retronas` and try and install something from the TUI to confirm retronas generally functions OK for you in the meantime

The installation through terminal goes smoothly for me. So, I'll use terminal for installation for the time being. Thanks.

**Comment by sairuk** [comment]
I've had some users on windows test this and they cannot recreate the issue. I am not considering this a RetroNAS issue anymore.

You can try 
- Firefox as an alternate browser
- check plugins 
- check browser settings
- try in incognito/private mode in your browser(s)
- flush your browser cache (previous incog test covers this)
- access the webui from a different machine and try again (or phone?)
- check for any 3rd party software you are running (security software etc) that may be preventing self-signed cert support


I'm going to close this because there is nothing further we can do. I've tested this across multiple installs and OS/devices and cannot replicate
