### ISSUE TITLE
Install "Samba for Mister" failed=1

### ISSUE THREAD

**Issue by xadox-1st** [danmons/retronas#263]
I have been using RetroNAS for the Mister for quite some time now.
When I update Samba for Mister, I get an error.

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=51   changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

How can you display which error is involved here in detail?

**Comment by sairuk** [comment]
the actual error would have been further up in the output or take a look at `/opt/retronas/log/ansible.log` after a mister run

**Comment by xadox-1st** [comment]
[ansible.log](https://github.com/danmons/retronas/files/10010585/ansible.log)
There are multiple failed ones.

**Comment by sairuk** [comment]
```
2022-11-15 08:16:52,609 p=124466 u=root n=ansible | failed: [localhost] (item=[{'src': 'nintendo/pokemini', 'last': '', 'mister': 'PokemonMini', 'retropie': '', 'batocera': 'pokemini', 'recalbox': 'pokemini', 'retroarch': '', 'ops2l': '', 'ps3netsrv': '', 'fspd': '', 'emuelec': 'pokemini', 'smdb': ''}, {'name': 'games', 'enabled': 'yes', 'generic': 'roms', 'systems': 'yes'}]) => {"ansible_loop_var": "item", "changed": false, "gid": 1000, "group": "service", "item": [{"batocera": "pokemini", "emuelec": "pokemini", "fspd": "", "last": "", "mister": "PokemonMini", "ops2l": "", "ps3netsrv": "", "recalbox": "pokemini", "retroarch": "", "retropie": "", "smdb": "", "src": "nintendo/pokemini"}, {"enabled": "yes", "generic": "roms", "name": "games", "systems": "yes"}], "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /mp0_data/mister/games/PokemonMini/../../roms/nintendo/pokemini", "owner": "service", "path": "/mp0_data/mister/games/PokemonMini", "size": 2, "src": "../../roms/nintendo/pokemini", "state": "directory", "uid": 1000}
```

from this error what is the output of the following commands

```
stat /mp0_data/mister/games/PokemonMini`
```
```
stat /mp0_data/roms/nintendo/pokemini
```

**Comment by xadox-1st** [comment]
`root@rn:~# stat /mp0_data/mister/games/PokemonMini
  File: /mp0_data/mister/games/PokemonMini
  Size: 2               Blocks: 1          IO Block: 512    directory
Device: 2bh/43d Inode: 296109      Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1000/ service)   Gid: ( 1000/ service)
Access: 2022-11-15 08:36:55.202342464 +0000
Modify: 2022-09-10 09:23:42.884927493 +0000
Change: 2022-09-10 09:23:42.884927493 +0000
 Birth: 2022-09-10 09:23:42.884927493 +0000
root@rn:~# stat /mp0_data/roms/nintendo/pokemini
  File: /mp0_data/roms/nintendo/pokemini
  Size: 2               Blocks: 1          IO Block: 131072 directory
Device: 2bh/43d Inode: 300620      Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1000/ service)   Gid: ( 1000/ service)
Access: 2022-11-15 08:36:55.254342420 +0000
Modify: 2022-11-15 08:29:05.922673368 +0000
Change: 2022-11-15 08:29:05.922673368 +0000
 Birth: 2022-11-15 08:29:05.922673368 +0000
`

**Comment by sairuk** [comment]
PokemonMini (as an example) should be a `link` not a `directory` on a properly setup RetroNAS.

Just a guess, since I ran into some new behaviour yesterday when I updated my own mister with `update_all.sh` and noted the script on the mister will create missing directories whereas RetroNAS uses links back to our generic dirs, I need to see if there is a setting to disable the auto folder creation for our doco. So we don't yet have a good solution for this, we need to look into it.

The way to work with mister and RetroNAS is to always update RetroNAS before `update_all.sh` although you'll need to be on the testing branch for the latest mister cores (see Updates -> Branch -> select testing

To workaround this manually, move any of the contents of the directories created by mister into the appropriate generic folder, remove the mister created folder on RetroNAS and rerun the MiSTer installer, this will create the appropriate links before you run `update_all.sh` or another updater script

based on your log these are your problem folders that need to be corrected
```
'Casio_PV-1000',
'eg2000',
'EpochGalaxyII',
'PokemonMini',
'SGB',
'TomyScramble',
'TomyTutor',
```


Example

yours
```
File: /mp0_data/mister/games/PokemonMini
Size: 2        	Blocks: 1          IO Block: 512 directory
```

mine
```
  File: /data/retronas/mister/games/PokemonMini -> ../../roms/nintendo/pokemini
  Size: 28        	Blocks: 0          IO Block: 4096   symbolic link
```

**Comment by sairuk** [comment]
we'll probably need to recommend this is set in the `update.ini` on the mister side from now on

```
#Specifies if the core directory (i.e. /media/fat/Amiga for Minimig core, /media/fat/SNES for SNES core) has to be created
#the first time the core is downloaded.
CREATE_CORES_DIRECTORIES="false"
```

**Comment by xadox-1st** [comment]
Thx for pointing that out.
>>The way to work with mister and RetroNAS is to always update RetroNAS before update_all.sh **although you'll need to be on the testing branch for the latest mister cores (see Updates -> Branch -> select testing)**

Already did so, but my problem was beeing still on the Stable Branch.
Switched to the Testing Brach and the problem is solved now.
