### ISSUE TITLE
I can't seem to get etherdfs to see 8.3 ~ conflict names correctly

### ISSUE THREAD

**Issue by Thraka** [danmons/retronas#309]
I've run through the https://github.com/danmons/retronas/wiki/FAT article a lot, trying different options, even trying to use `-t vfat` with more options specified but no matter that or `-t msdos` I just don't get the truncated names to appear correctly. Spaces even show in the names when they shouldn't. For example:

`new file document 1.txt` simply appears as `new file.txt` with the space, which is invalid, and I can't edit the file from the dos computer. It's listed, but not touchable. If the file is renamed to `newfiledocument1.txt` it's listed as `newfiled.txt`. When there are two of them, `newfiledocument1.txt` and `newfiledocument2.txt`, I see two entries for `newfiled.txt`. So the ~1 isn't being appended to the files when they're invalid for MSDOS.

Any idea how to fix this?

**Comment by danmons** [comment]
At a file system level (ignoring EtherDFS for a moment), I see the "~" notation for files if I use `-t msdos` instead of `-t vfat` on a file system. Here's a from-scratch example:

```
# lvcreate --name dos --size 1G vg0
  Logical volume "dos" created.

# mkfs.msdos /dev/vg0/dos
mkfs.fat 4.2 (2021-01-31)

# mkdir -pv /mnt/dos

# mount -t msdos /dev/vg0/dos /mnt/dos
# touch 'this is a long filename.txt'
# cp this\ is\ a\ long\ filename.txt /mnt/dos
cp: cannot create regular file '/mnt/dos/this is a long filename.txt': Invalid argument

# umount /mnt/dos
# mount -t vfat /dev/vg0/dos /mnt/dos
# cp this\ is\ a\ long\ filename.txt /mnt/dos
# find /mnt/dos
/mnt/dos
/mnt/dos/this is a long filename.txt

# umount /mnt/dos
# mount -t msdos /dev/vg0/dos /mnt/dos
# find /mnt/dos
/mnt/dos
/mnt/dos/thisis~1.txt
```

So this is all working as intended if the file system is mounted with `-t msdos`, however as you can see from the output above you cannot copy/create files with longer than 8.3 filenames.  If they exist already (i.e.: previous written by a Linux machine using `mount -t vfat` or a Windows machine with the volume mounted locally), they'll be truncated on read.  This is a filesystem level thing, not an EtherDFS thing. 

For EtherDFS itself, and I hate to do this to you (I don't like projects that say "not our issue, see upstream"), but this isn't a RetroNAS thing.

EtherDFS is an excellent project, but it's intentionally simple to keep the code base down and the protocol lightweight.  We mention in the readme that part of the "joy" of retro computing are issues like these, and that 8.3 filenames are part of good housekeeping for using old computers (not limited to either EtherDFS nor MS-DOS. This affects lots of older computers, file systems and operating systems). 

I think from here you're either going to need to engage the author of EtherDFS and see if they have any suggestions when it comes to dealing with long filenames outside of a local filesystem mounted with `-t msdos`.  Either that, or just manually ensure you are taking the steps to ensure 8.3 filenames with systems that expect it. 

The main project is here:
* https://etherdfs.sourceforge.net/

And in particular check the `ethersrv-linux.txt` file on that page which documents in detail the expectations of the underlying file system when hosted on a Linux server.

**Comment by Thraka** [comment]
Thank you for the extensive reply!

**Comment by Thraka** [comment]
Ahhhh you identified the problem. Ether is indeed working! I created the mount originally as msdos, then when the drive was added to fstab via the web interface and the system rebooted, it had reverted to "auto" and I didn't notice. So when I was testing the results seemed the same as vfat. Since msdos has less options to tweak than vfat I swapped to vfat and started trying to configure the mount options to replicate msdos.

So now I just modified fstab to set the type to msdos and everything works as expected. Thanks again @danmons
