### ISSUE TITLE
RetroNAS updater does not respect system proxy configuration

### ISSUE THREAD

**Issue by DanAE111** [danmons/retronas#318]
I have environmental variables applied to my system to direct it to a proxy server on my local network. So if i run export as a user logged into the system (including the retronas user) i can see my proxy variables set.

Let's say...

```
http_proxy=http://proxy.ultranet.xyz:3128/
https_proxy=https://proxy.ultranet.xyz:3128/
ftp_proxy=ftp://proxy.ultranet.xyz:3128/
socks_proxy=https://proxy.ultranet.xyz:3128/
```

That's all working fine, other applications respect the configuration and are able to make their requests as you'd expect. RetroNAS on the other hand looks to be losing those variables somewhere along the way, i did some digging through the config files and updater script but i'm not sure where things are going wrong.

When i go to update RetroNAS from the menu i get a quick flash on screen of the git command running with a 403 error (which is expected for a denied site in my proxy configuration). Nothing appears in my proxy logs, i've tested outside of RetroNAS and was able to successfully clone the repo and see that activity hit the proxy i have configured.

I'm leaning towards the assumption that RetroNAS when its runs does a few things to control which environmental variables are in place or has a specific configuration for git that overrides the system proxy?

**Comment by sairuk** [comment]
we're not doing anything in particular with updater, i can force a failure on the updater by installing a non-existent proxy in `/etc/environment` and see git is attempting to use the proxy, so it does try to use it.

```
root@testronas:/opt/retronas/scripts/static# env | grep -i proxy
ftp_proxy=ftp://proxy.ultranet.xyz:3128/
https_proxy=https://proxy.ultranet.xyz:3128/
socks_proxy=https://proxy.ultranet.xyz:3128/
http_proxy=http://proxy.ultranet.xyz:3128/
root@testronas:/opt/retronas/scripts/static# 
```

```
root@testronas:/opt/retronas/scripts/static# ./update-retronas.sh 
Updating files: 100% (249/249), done.
HEAD is now at 2f5ecda Merge branch 'testing' of https://github.com/danmons/retronas into testing
fatal: unable to access 'https://github.com/danmons/retronas.git/': Could not resolve proxy: proxy.ultranet.xyz
root@testronas:/opt/retronas/scripts/static# 
```

**Comment by sairuk** [comment]
I see when running from the menu where we execute another bash session during `script_runner.sh` the environment does not pickup the existing `/etc/environment`

**Comment by danmons** [comment]
So background - I work a lot in complex Linux environments sitting behind corporate proxies, so I'm very familiar with this pain. 

First up, there are zero standards with proxies.  You'll find applications that honour `$http_proxy`, others that honour `$HTTP_PROXY`, some that honour both but randomly depending on things, some that honour neither.  

Likewise SOCKS proxying is even rarer.  Very unusual for apps to support that (common in browsers, very rare in CLI tools). 

Worth noting that there is NO STANDARD for FTP proxying.  Various implementations of FTP can handle what is essentially a remote shell (first FTP server FTPs into second, initiates remote push/pull command, streams data back to first and then back to client).  Some tools attempt to FTP over HTTP proxies, but again this is non-standard.  So if your actual data pull must be done via FTP (e.g..: to an `ftp://` style URI, or via a tool like `ncftp`), then that is a whole other mess. 

Secondly, if you export these as a given user, things like `sudo` or `su -` commands will forget these due to envar handling and either security (sudo needs specific help keeping envars across account) or session handling (`su -` specifically loses the previous session to ensure cleanliness of the new shell). 

As @sairuk said above, these are best set in places like `/etc/environment` and `/etc/profile.d` (I use the latter, couldn't comment on the firmer).  I would put in at least the following (for example, if I had a standard Squid install listening on `yourproxy:3128` somewhere in my network):

Create a file called `/etc/profile.d/proxy.sh` as mode 644, and full it with:

```
export proxy="http://yourproxy:3128"
export PROXY="${proxy}"
export http_proxy="${proxy}"
export HTTP_PROXY="${proxy}"
export https_proxy="${proxy}"
export HTTPS_PROXY="${proxy}"
export all_proxy="${proxy}"
export ALL_PROXY="${proxy}"
export no_proxy='127.*, 192.168.*, 10.*, anythingelse*, onlyworkswithfirstpart*, cantputinCIDRnotation*'
export NO_PROXY="${no_proxy}"
```

From here, any new shell invoked, including things like `su -` and `#!/bin/bash` will have these applied and work for simple tools doing HTTP or HTTP requests (e.g.: `curl` or `wget`, and I'm fairly certain `git` pulling from a HTTPS repo, but definitely not from an SSH repo).  But again, whether or not the tool used internally in our scripts supports it is a complete roll of the dice.  

Remember to log out fully and log back in for this to work in user shells.  If you have services you need to pass this to, you'll need to add things to the individual systemd units.   Cron jobs should inherit this post-reboot.

**Comment by sairuk** [comment]
environment was not being preserved in the startup script, pushed a fix

**Comment by DanAE111** [comment]
@sairuk made that simple change to `/usr/loca/bin/retronas` and that did the trick!

@danmons appreciate the clarification with the proxy variables nothing online mentioned the potential horrors of applications picking and choosing between the variables set in both upper and lowercase. I've got mine set in both `/etc/environment` and `/etc/profile.d` which so far is working well.

**Comment by sairuk** [comment]
As reported issue is resolved, thanks for the report
