### ISSUE TITLE
Cockpit network manager broke retronas

### ISSUE THREAD

**Issue by Braincell1973** [danmons/retronas#334]
I did a fresh install of retronas on a 32gb card on pi4, using an external 4tb exfat drive I got it mounted etc but in cockpit there is a "networkmamager" option, I selected this and it broke retronas, I immediately lost samba from Windows and cockpit disconnected , I had a screen and keyboard currently plugged into the pi and did a sudo reboot, when it came back up I could not start retronas, it complains about the retronas.cfg file line 57 (my ips ??)

**Comment by sairuk** [comment]
this wont be a problem with retronas specifically, although lets see what we can work out.

cockpit by default runs in limited access mode when logged in as the retronas user and they cant make networking changes, i've reinstalled cockpit today on my test box (not an rpi4) and it doesn't do anything when selected.

What base image did you install to the rpi4 sd?

Can you still get to a terminal as a local user? if so run `ip -4 br a` that should return something like
```
root@testronas:~# ip -4 -br a
lo               UNKNOWN        127.0.0.1/8 
ens192           UP             192.168.0.123/24 
root@testronas:~# 
```
we filter out the lo interface when detecting ip addresses

i am guessing the the error you mentioned is because the $MYIPS var is empty and we try to export it later on, if you can capture the error it would help

**Comment by Braincell1973** [comment]
Yes that is exactly the error, I will capture the output later, I followed the guide and installed the raspios 64bit lite and did apt update etc 

I do still have access to the command line but cannot start retronas

**Comment by Braincell1973** [comment]
I cannot ssh in either but booting with a display and keyboard connected to the pi4 and entering:
Ip -4 -br a

I get

Lo      UNKNOWN        127.0.0.1/8

That's all that's returned.

When I try running retronas I get:

/opt/retronas/config/retronas.cfg: line 57: MY_IPS: unbound variable

If I run ifconfig I notice my wireless just displays zeros for all packet transfers but says it is UP if that helps

**Comment by Braincell1973** [comment]
OK, so it seems that selecting the network manager broke the wireless component......

I re-ran raspi-config and re-entered the wireless said and pass and on reboot the system worked as it should ssh/samba etc all restored to working status......

**Comment by sairuk** [comment]
interesting, but as expected this isn't a retronas fix, it would need to be raised with the rpi or cockpit folks. thanks for letting us know you got it working
