### ISSUE TITLE
Web GUI open questions

### ISSUE THREAD

**Issue by FlotterCodername** [danmons/retronas#35]
I'm working on a web GUI [over here](https://github.com/FlotterCodername/retronas) (early and non-functional)
There are a bunch questions that should be addressed rather sooner than later:

### Root privilige handling.
I'd rather not run the whole thing as root. Maybe better to have a separate process that can execute pre-defined stuff with root priviliges.
### The multi-user problem
@danmons knows the project in and out. Do we have to ensure that only one user is doing stuff at the same time?
### CSS
I can do some basic stuff, but it's not going to look cream-of-the-crop. Help very much appreciated
### Generating web GUI options from TUI
I have a very basic proof-of-concept of this working, but it's really going to need some specific begin-end comment markers and separators (e.g. between tool name and description) to work *well*.
### Some little technical details
Will ask Dan directly

**Comment by FlotterCodername** [comment]
Picture for any interested parties
![sneak peek](https://user-images.githubusercontent.com/4962476/152613903-26a83bcb-d56e-4f1f-bf74-cd6afeb702b5.png)

**Comment by sairuk** [comment]
May I suggest that this is moved to Discussions with issues left for found problems with RetroNAS. It may be better suited there since this is not particularly an issue with the project more of a technical discussion with a new feature set. 

https://github.com/danmons/retronas/discussions

I also did this recently with the TCPser thread before i realised discussions were open for this project, I ended up closing my (non)issue and moved it to discussions

**Comment by FlotterCodername** [comment]
Ah right, that's a thing that exists! Will do
