### ISSUE TITLE
Permissions problem with MacOS SMB

### ISSUE THREAD

**Issue by aminta** [danmons/retronas#352]
I'm on Mac M1 Ventura 13.5.1, I've set a 16TB USB storage in retronas + samba + samba MiSTer as pi user on my Raspberry Pi4, fixed all permissions, then I successfully log in from MAC to retronas SMB as pi, but I can only create new files / folders, not delete existing ones (for example, I want use only some games directories in "MiSTer" and not use the "saves" dir...

Logging in Rasp as pi user and deleting a dire in mister with "rm -r saves" works...

[EDIT] Ok, I've tried to delete a subfolder of "saves" like "Adam" and the problem is that Finder says that the element is "in use"...

**Comment by sairuk** [comment]
you'll need to do this from the server side, retronas is not setup for custom dir management, running the installer again will recreate all the folders

**Comment by aminta** [comment]
OK, I understand that running the installer again will recreate all the folders, what I don't understand is why I can't delete some folders having the permissions to do that.

**Comment by sairuk** [comment]
The documentation for the samba project is available here https://www.samba.org/samba/docs/

afaik this is a limitation using symlinks with samba, they are not standard directories even though they present as such on the share. This issue is not limited to mac, i have a similar issue on linux clients accessing over samba and if i find a solution i'll implement a fix but i don't know of one atm.

you can however rename the folder as a workaround so the mister doesn't find them or remove them serverside

**Comment by aminta** [comment]
Ok, now it's clear, thanks!
