### ISSUE TITLE
PCEngine / NEC Symlinks Failing

### ISSUE THREAD

**Issue by ChaOConnor** [danmons/retronas#52]
This just started happening, not sure if a recent commit changes something, just posting here for awareness.  Thanks!

```
TASK [Generic ROM dir - build NEC symlinks] ***************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item={'src': 'pcengine', 'dest': 'turbografx16'})
failed: [localhost] (item={'src': 'pcengine/iso', 'dest': 'pcenginecd'}) => {"ansible_loop_var": "item", "changed": false, "gid": 1000, "group": "cha", "item": {"dest": "pcenginecd", "src": "pcengine/iso"}, "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /mnt/nfs/storage/roms/nec/pcenginecd/pcengine/iso", "owner": "cha", "path": "/mnt/nfs/storage/roms/nec/pcenginecd", "size": 10, "src": "pcengine/iso", "state": "directory", "uid": 1000}
ok: [localhost] => (item={'src': 'pcengine/iso', 'dest': 'turbografxcd'})
```

**Comment by danmons** [comment]
This came as a recent re-shuffle of symlinks to better serve systems where a single emulator did both PCEngine and PCEngineCDROM (MiSTer, for example).

Due to the way Ansible doesn't force-overwrite files (by my choice - I don't want it deleting people's stuff), it means this tool will fail if there are on-disk conflicts.

Steps to resolve:

1) Rename your `roms/nec` folder to something like `roms/nec.old`. You can do this via SMB/CIFS from a Windows or Mac desktop.

2) Re-run your tool installer of choice

3) Again in Windows/Mac if you like, cut and paste the ROMs from `nec.old` into the right place in `nec`.  Because this is a "move" filesystem operation on the same mounted filesystem, it will be instant.

Apologies for this breakage, but it was necessary to accommodate external software better, and not delete any on-disk content that people had.  Hopefully it doesn't happen too often from here on (although we still are officially in alpha, so things may change for a short while until the project settles into a stable state).

**Comment by ChaOConnor** [comment]
No worries and you have nothing to apologize for, thank you as always!!!
